export const STORE_COMPONENT_HEADER_DATA = "STORE_COMPONENT_HEADER_DATA";
export const SET_COMPONENT_HEADER_DATA = "SET_COMPONENT_HEADER_DATA";
export const GET_COMPONENT_HEADER_DATA = "GET_COMPONENT_HEADER_DATA";
// export const HIDE_HOST = "HIDE_HOST";
